<#
.SYNOPSIS
Restores a backup created by backup-full-database.ps1 into Supabase.

.EXAMPLE
.\scripts\ops\restore-full-database.ps1 `
  -BackupDirectory ".\backups\database\source-ref-20260916T100000Z" `
  -TargetDatabaseUrl $env:TARGET_DATABASE_URL `
  -TargetProjectRef "target-ref" `
  -Mode NewProject `
  -Confirmation "RESTORE:target-ref"

.EXAMPLE
.\scripts\ops\restore-full-database.ps1 `
  -BackupDirectory $backup `
  -TargetDatabaseUrl $env:TARGET_DATABASE_URL `
  -TargetProjectRef "target-ref" `
  -Mode ReplaceData `
  -Confirmation "REPLACE-DATA:target-ref"
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$BackupDirectory,

  [Parameter()]
  [string]$TargetDatabaseUrl = $env:TARGET_DATABASE_URL,

  [Parameter(Mandatory = $true)]
  [string]$TargetProjectRef,

  [Parameter(Mandatory = $true)]
  [ValidateSet("NewProject", "ReplaceData")]
  [string]$Mode,

  [Parameter(Mandatory = $true)]
  [string]$Confirmation,

  [Parameter()]
  [switch]$SkipSafetyBackup
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path

function Get-ProjectRefFromUrl {
  param([string]$Url)

  if ($Url -match "@db\.([a-z0-9-]+)\.supabase\.co") {
    return $Matches[1]
  }
  if ($Url -match "postgres(?:ql)?://postgres\.([a-z0-9-]+):") {
    return $Matches[1]
  }
  return ""
}

function Assert-Command {
  param([string]$Name, [string]$InstallHint)

  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if (-not $command) {
    throw "Required command '$Name' was not found. $InstallHint"
  }
  return $command.Source
}

function Invoke-Psql {
  param(
    [string]$Psql,
    [string[]]$Arguments,
    [string]$Description
  )

  Write-Host $Description
  $previousPreference = $ErrorActionPreference
  try {
    $ErrorActionPreference = "Continue"
    & $Psql @Arguments
    $nativeExitCode = $LASTEXITCODE
  } finally {
    $ErrorActionPreference = $previousPreference
  }
  if ($nativeExitCode -ne 0) {
    throw "$Description failed with exit code $nativeExitCode."
  }
}

function Get-CopyTables {
  param([string[]]$SqlPaths)

  $tables = New-Object "System.Collections.Generic.HashSet[string]"
  foreach ($sqlPath in $SqlPaths) {
    if (-not (Test-Path -LiteralPath $sqlPath -PathType Leaf)) {
      continue
    }
    $reader = [System.IO.File]::OpenText($sqlPath)
    try {
      while (($line = $reader.ReadLine()) -ne $null) {
        if ($line -match '^COPY\s+(.+?)\s+\(') {
          $table = $Matches[1]
          $identifier = '(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$]*)'
          if ($table -notmatch "^$identifier\.$identifier$") {
            throw "Unsafe or unsupported COPY target in backup: $table"
          }
          [void]$tables.Add($table)
        }
      }
    } finally {
      $reader.Dispose()
    }
  }
  return @($tables | Sort-Object)
}

function Write-TruncateSql {
  param([string[]]$Tables, [string]$Path)

  $lines = New-Object "System.Collections.Generic.List[string]"
  $lines.Add("-- Generated by restore-full-database.ps1")
  $lines.Add("SET statement_timeout = 0;")
  if ($Tables.Count -gt 0) {
    # Truncate the complete backed-up set in one statement so source FKs are
    # satisfied. Deliberately omit CASCADE: a target-only dependent table must
    # abort the transaction rather than be silently erased.
    $lines.Add("TRUNCATE TABLE " + ($Tables -join ", ") + " RESTART IDENTITY;")
  }
  [System.IO.File]::WriteAllLines($Path, $lines, (New-Object System.Text.UTF8Encoding($false)))
}

function Split-QualifiedName {
  param([string]$Name)

  $identifier = '(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$]*)'
  $match = [regex]::Match($Name, "^(?<schema>$identifier)\.(?<object>$identifier)$")
  if (-not $match.Success) {
    throw "Unsupported qualified SQL identifier in backup: $Name"
  }
  $schema = $match.Groups["schema"].Value
  $object = $match.Groups["object"].Value
  if ($schema.StartsWith('"')) {
    $schema = $schema.Substring(1, $schema.Length - 2).Replace('""', '"')
  }
  if ($object.StartsWith('"')) {
    $object = $object.Substring(1, $object.Length - 2).Replace('""', '"')
  }
  return @($schema, $object)
}

function Write-TransactionalVerificationSql {
  param([object]$Manifest, [string]$Path)

  $lines = New-Object "System.Collections.Generic.List[string]"
  $lines.Add("-- Generated verification; failure rolls back the restore transaction.")
  $lines.Add("CREATE TEMP TABLE ccshau_expected_restore_counts(schema_name text, table_name text, expected_count bigint);")
  foreach ($property in $Manifest.inventory.rowCounts.PSObject.Properties) {
    $parts = Split-QualifiedName -Name ([string]$property.Name)
    $schemaName = $parts[0].Replace("'", "''")
    $tableName = $parts[1].Replace("'", "''")
    $expectedCount = [long]$property.Value
    $lines.Add("INSERT INTO ccshau_expected_restore_counts VALUES ('$schemaName', '$tableName', $expectedCount);")
  }
  $lines.Add(@"
DO `$restore_verify`$
DECLARE
  item record;
  counted bigint;
BEGIN
  FOR item IN SELECT * FROM ccshau_expected_restore_counts LOOP
    EXECUTE format('SELECT count(*) FROM %I.%I', item.schema_name, item.table_name) INTO counted;
    IF counted <> item.expected_count THEN
      RAISE EXCEPTION 'Restore row-count mismatch for %.%: expected %, found %',
        item.schema_name, item.table_name, item.expected_count, counted;
    END IF;
  END LOOP;
END
`$restore_verify`$;
"@)
  [System.IO.File]::WriteAllLines($Path, $lines, (New-Object System.Text.UTF8Encoding($false)))
}

function Assert-Checksums {
  param([string]$Directory, [object]$Manifest)

  $artifactEntries = @($Manifest.artifacts)
  $artifactNames = @($artifactEntries | ForEach-Object { [string]$_.file })
  $requiredNames = @("roles.sql", "schema.sql", "data.sql", "history_schema.sql", "history_data.sql")
  if ($artifactNames.Count -ne $requiredNames.Count) {
    throw "Manifest must contain exactly the five required SQL artifacts."
  }
  foreach ($requiredName in $requiredNames) {
    if (@($artifactNames | Where-Object { $_ -ceq $requiredName }).Count -ne 1) {
      throw "Manifest must contain exactly one checksum entry for $requiredName."
    }
  }
  if (@($artifactNames | Select-Object -Unique).Count -ne $artifactNames.Count) {
    throw "Manifest contains duplicate artifact entries."
  }

  foreach ($artifact in $Manifest.artifacts) {
    $path = Join-Path $Directory ([string]$artifact.file)
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
      throw "Backup artifact is missing: $($artifact.file)"
    }
    $actual = (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actual -ne ([string]$artifact.sha256).ToLowerInvariant()) {
      throw "Checksum mismatch for $($artifact.file). The backup may be incomplete or modified."
    }
  }
}

if ([string]::IsNullOrWhiteSpace($TargetDatabaseUrl)) {
  throw "Target database URL is required. Set TARGET_DATABASE_URL or pass -TargetDatabaseUrl."
}

$derivedTargetRef = Get-ProjectRefFromUrl -Url $TargetDatabaseUrl
if ([string]::IsNullOrWhiteSpace($derivedTargetRef)) {
  throw "The target project reference could not be derived from the database URL. Use a Supabase direct or Session Pooler URL whose host/user contains the project reference."
}
if ($derivedTargetRef -ne $TargetProjectRef) {
  throw "TargetProjectRef does not match the target database URL."
}

$expectedConfirmation = if ($Mode -eq "ReplaceData") {
  "REPLACE-DATA:$TargetProjectRef"
} else {
  "RESTORE:$TargetProjectRef"
}
if ($Confirmation -cne $expectedConfirmation) {
  throw "Confirmation mismatch. Pass -Confirmation `"$expectedConfirmation`" to continue."
}

$BackupDirectory = (Resolve-Path -LiteralPath $BackupDirectory).Path
$manifestPath = Join-Path $BackupDirectory "manifest.json"
if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
  throw "manifest.json was not found in the backup directory."
}
$manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
if ([int]$manifest.formatVersion -ne 2) {
  throw "Unsupported backup format version: $($manifest.formatVersion)"
}
Assert-Checksums -Directory $BackupDirectory -Manifest $manifest

$sourceProjectRef = [string]$manifest.sourceProjectRef
if ($Mode -eq "NewProject" -and $sourceProjectRef -eq $TargetProjectRef) {
  throw "NewProject mode cannot target the source project. Use ReplaceData for a same-project data rollback."
}

$psql = Assert-Command -Name "psql" -InstallHint "Install PostgreSQL 15+ command-line tools and add their bin directory to PATH."
$previousErrorActionPreference = $ErrorActionPreference
try {
  $ErrorActionPreference = "Continue"
  $psqlVersionText = (& $psql --version 2>$null | Out-String).Trim()
  $psqlVersionExitCode = $LASTEXITCODE
} finally {
  $ErrorActionPreference = $previousErrorActionPreference
}
if ($psqlVersionExitCode -ne 0) {
  throw "Could not run psql to determine its version."
}
if ($psqlVersionText -notmatch '(\d+)(?:\.\d+)?') {
  throw "Could not determine the psql version."
}
if ([int]$Matches[1] -lt 15) {
  throw "PostgreSQL client 15 or newer is required. Found: $psqlVersionText"
}

$rolesPath = Join-Path $BackupDirectory "roles.sql"
$schemaPath = Join-Path $BackupDirectory "schema.sql"
$dataPath = Join-Path $BackupDirectory "data.sql"
$historySchemaPath = Join-Path $BackupDirectory "history_schema.sql"
$historyDataPath = Join-Path $BackupDirectory "history_data.sql"
foreach ($requiredPath in @($rolesPath, $schemaPath, $dataPath, $historySchemaPath, $historyDataPath)) {
  if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
    throw "Required restore file is missing: $requiredPath"
  }
}

if ($Mode -eq "ReplaceData" -and -not $SkipSafetyBackup) {
  Write-Host "Creating mandatory pre-restore safety backup of target project..."
  $safetyRoot = Join-Path $RepoRoot "backups\pre-restore"
  & (Join-Path $PSScriptRoot "backup-full-database.ps1") `
    -DatabaseUrl $TargetDatabaseUrl `
    -ProjectRef $TargetProjectRef `
    -OutputRoot $safetyRoot
  if ($LASTEXITCODE -ne 0) {
    throw "Target safety backup failed. Restore aborted without changing the database."
  }
}

$tempDir = Join-Path ([System.IO.Path]::GetTempPath()) ("ccshau-restore-" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tempDir -Force | Out-Null

try {
  $restoreArgs = New-Object "System.Collections.Generic.List[string]"
  $transactionVerifyPath = Join-Path $tempDir "verify-before-commit.sql"
  Write-TransactionalVerificationSql -Manifest $manifest -Path $transactionVerifyPath
  $restoreArgs.Add("--single-transaction")
  $restoreArgs.Add("--variable")
  $restoreArgs.Add("ON_ERROR_STOP=1")

  if ($Mode -eq "NewProject") {
    $restoreArgs.Add("--file")
    $restoreArgs.Add($rolesPath)
    $restoreArgs.Add("--file")
    $restoreArgs.Add($schemaPath)
    $restoreArgs.Add("--command")
    $restoreArgs.Add("SET session_replication_role = replica")
    $restoreArgs.Add("--file")
    $restoreArgs.Add($dataPath)

    $restoreArgs.Add("--file")
    $restoreArgs.Add($historySchemaPath)
    $restoreArgs.Add("--file")
    $restoreArgs.Add($historyDataPath)
  } else {
    # Same-project logical rollback is data-only. Replacing a hosted
    # Supabase project's managed schemas with DROP SCHEMA is unsupported.
    # Verify schema compatibility before truncating any target rows.
    & (Join-Path $PSScriptRoot "verify-full-database.ps1") `
      -BackupDirectory $BackupDirectory `
      -DatabaseUrl $TargetDatabaseUrl `
      -ProjectRef $TargetProjectRef `
      -SkipRowCounts

    $copySqlFiles = @($dataPath)
    $copySqlFiles += $historyDataPath
    $copyTables = Get-CopyTables -SqlPaths $copySqlFiles
    $truncatePath = Join-Path $tempDir "truncate-backed-up-tables.sql"
    Write-TruncateSql -Tables $copyTables -Path $truncatePath

    $restoreArgs.Add("--file")
    $restoreArgs.Add($truncatePath)
    $restoreArgs.Add("--command")
    $restoreArgs.Add("SET session_replication_role = replica")
    $restoreArgs.Add("--file")
    $restoreArgs.Add($dataPath)

    $restoreArgs.Add("--file")
    $restoreArgs.Add($historyDataPath)
  }

  $restoreArgs.Add("--file")
  $restoreArgs.Add($transactionVerifyPath)
  $restoreArgs.Add("--dbname")
  $restoreArgs.Add($TargetDatabaseUrl)
  Invoke-Psql -Psql $psql -Arguments $restoreArgs.ToArray() -Description "Restoring database backup in one transaction..."

  & (Join-Path $PSScriptRoot "verify-full-database.ps1") `
    -BackupDirectory $BackupDirectory `
    -DatabaseUrl $TargetDatabaseUrl `
    -ProjectRef $TargetProjectRef

  Write-Host ""
  Write-Host "Restore completed successfully."
  Write-Host "Target project: $TargetProjectRef"
  Write-Host "Mode: $Mode"
  Write-Host "Important: Storage object files were not restored."
  if ($sourceProjectRef -ne $TargetProjectRef) {
    Write-Host "Users must sign in again if the target project uses a different JWT secret."
  }
} finally {
  if (Test-Path -LiteralPath $tempDir) {
    Remove-Item -LiteralPath $tempDir -Recurse -Force
  }
}
